### PR TITLE
fix: reduce Docker registry pull requests

### PR DESCRIPTION
**Pull request by KSmanis**
Circumvent the Docker Hub rate limit triggered by pushing the multiarch manifests after *every* image is built and pushed. Instead, deploy the manifests only after *all* images have been built and pushed.

### CODE REVIEW

**Comment by KSmanis** [comment]
`stage3` builds have been failing for some time due to the Docker Hub rate limit. This PR addresses this issue.

**Comment by ultrabug** [comment]
Thanks @KSmanis from a first glance this looks okay but maybe @ajakk could spare also time eyes on it?

**Comment by KSmanis** [comment]
I've merged it in my fork's master, in case you are interested in inspecting the build process:
[Monday, July 29](https://github.com/KSmanis/gentoo-docker-images/actions/runs/10136605326)
[Monday, August 5](https://github.com/KSmanis/gentoo-docker-images/actions/runs/10241107482)

**Comment by ajakk** [comment]
Thank you, sorry for the delay!

**Comment by ajakk** [comment]
Uhoh, a pair of failures: https://github.com/gentoo/gentoo-docker-images/actions/runs/10763706541

**Comment by KSmanis** [comment]
@ajakk https://github.com/gentoo/gentoo-docker-images/commit/a1f9522037f7e3d46dec51c8a4d4e37ca4c34732 should have also removed the `stage3:hardened-nomultilib` manifest @ https://github.com/gentoo/gentoo-docker-images/blob/master/deploy-manifests.sh#L25

**Comment by ajakk** [comment]
@KSmanis any chance you could take a look at the newest failures? Seems like a difference between how `TARGET` is handled between the deploy types?

**Comment by KSmanis** [comment]
They seem like transient Docker Hub errors to me. I'll keep an eye on them in any case.

**Comment by ajakk** [comment]
Ah, yeah, looks like my rerun yielded a slightly different error that looked like something else and then my later commits outright passed. Oh well. Thanks!

**Pull request closed without merging**
