### PR TITLE
Add amd64 desktop systemd

### PR DESCRIPTION
**Pull request by td5038**
I know, no one asked for these containers, but I added them myself. @mgorny I need to see results in CI.

### CODE REVIEW

**Comment by ajakk** [comment]
Well.. I'd run the CI here, but I don't have a button or anything for it? Maybe you could rebase?

**Comment by thesamesam** [comment]
please squash, but then sounds good (was wanting this myself)

**Comment by ultrabug** [comment]
CI needs #132 first

**Comment by ajakk** [comment]
Note that in the future it might be easier to `git pull --rebase` or `git rebase master` rather than deal with merges in your own branch. Thank you!

**Pull request closed without merging**
