### PR TITLE
Update stage3 build targets

### PR DESCRIPTION
**Pull request by KSmanis**
* Add support for amd64/x86 uclibc stage3 builds
* Remove support for stale armv7a stage3 build

### CODE REVIEW

**Comment by KSmanis** [comment]
All builds should pass with this changeset.

**Comment by mjeveritt** [comment]
No reason not to add in arm64 targets too - you'll find them presently in 'experimental' but there should be provision in the script to pull from there too ..

**Comment by mjeveritt** [comment]
Updating the README would be good also! :+1:

**Comment by KSmanis** [comment]
Although ARM builds are successful, I'm not sure if all of them make sense in the first place, since Docker only officially supports `arm32v6`, `arm32v7`, and `arm64v8` ([Source](https://github.com/docker-library/official-images#architectures-other-than-amd64)). I'll have to investigate further to understand what's really going on. For now, let's just drop the stale armv7a target, since it dates from 2016 and it fails the CI for quite some time.

**Comment by KSmanis** [comment]
I will open a new PR with support for most architectures.

**Pull request closed without merging**
