### PR TITLE
Fixing /bin/sh: /build.sh: Permission denied

### PR DESCRIPTION
**Pull request by goors**
Fixing /bin/sh: /build.sh: Permission denied

### CODE REVIEW

**Comment by alunduil** [comment]
It seems like it would be cleaner to just invoke the shell on it.  Would that be better?

**Comment by dastergon** [comment]
As seen [here](https://github.com/gentoo/gentoo-docker-images/blame/master/amd64-hardened/build.sh) build.sh scripts have already 0755 permissions

**Comment by alunduil** [comment]
@dastergon docker has begun stripping executable permissions in certain cases.  We need verification inside the container of those permissions.

**Comment by mrueg** [comment]
I've changed the way the images are build, so this is not required anymore.

**Pull request closed without merging**
