### PR TITLE
add in hardened profile

### PR DESCRIPTION
**Pull request by necrose99**
Security overlay/s testing against x86-hardened.
docker pull gentoo/stage3-x86-hardened would be of great convince.

### CODE REVIEW

**Comment by necrose99** [comment]
having issues on docker hub , been tinkering about, 
if it want for the basis of a custom Live CD CHROOT for usb key for work related (un-docker) old as hell PC's i'd not even ask.

**Comment by ChaosEngine** [comment]
I've been only testing x86* on virtualbox ubuntu-x86 and partially. As I recall I've used https://github.com/docker-32bit/ubuntu as source of docker engine on x86. But don't really remember.

**Comment by necrose99** [comment]
x86 works might just have to overlay portage and and swap to hardened profile and pull in hardened tarball and over-write https://hub.docker.com/r/necrose99/gentoo-docker-x86/builds/

**Comment by necrose99** [comment]
sorry for the commit spam , but when theirs a WILL theirs me beating it with a scythe till the issue DIES. 

https://hub.docker.com/r/necrose99/gentoo-x86-hardened/builds/buoh56byzkwrzsqajte6qxr/

FROM SCRATCH 
ADD URL to STAGE 3 TARBALL.

**Comment by dastergon** [comment]
Could you please squash the commits?

**Comment by mrueg** [comment]
Thanks, I added it in a different way see: https://github.com/gentoo/gentoo-docker-images/issues/41

**Pull request closed without merging**
