### PR TITLE
Added a multi-stage build example using portage to README.md.

### LINKED ISSUE #35: Can't install package from Dockerfile
If you try something like this:

``` Dockerfile
FROM gentoo/stage3-amd64

RUN emerge -qv www-servers/apache
```

You will get: 

``` bash
!!! Section 'x-portage' in repos.conf has location attribute set to nonexistent directory: '/usr/portage'
!!! Section 'gentoo' in repos.conf has location attribute set to nonexistent directory: '/usr/portage'
!!! Invalid Repository Location (not a dir): '/usr/portage'


!!! /etc/portage/make.profile is not a symlink and will probably prevent most merges.
!!! It should point into a profile within /usr/portage/profiles/
!!! (You can safely ignore this message when syncing. It's harmless.)


!!! Your current profile is invalid. If you have just changed your profile
!!! configuration, you should revert back to the previous configuration.
!!! Allowed actions are limited to --help, --info, --search, --sync, and
!!! --version.
```

This is because of the separation of portage structure on another image. On running image it's working.

Here is my `docker-compose.yml` file:

```yaml
portage:
  image: gentoo/portage

nx-default:
  build: docker/gentoo
  hostname: nx-default.nexylan.net
  volumes_from:
    - portage
  links:
    - influxdb
```

I'm not an expert but why separating Portage? Because of this, we can't install package on image building.

Regards.

### PR DESCRIPTION
**Pull request by javabrett**
Fixed #35.

### CODE REVIEW

**Comment by mrueg** [comment]
Looks good to me! Thanks.

**Comment by simonvanderveldt** [comment]
What is the thing you're trying to do?

Generally it's not recommended to keep the package cache (which the portage image effectively is) within an image.
For use as a "base image" it's useless because it gets outdated pretty much immediately and for use as in the example to install a package it adds a significant amount of size to the image.
It's cleaner to just do a `emerge-webrsync && emerge <package> && rm -rf /usr/portage` for that use case.

**Comment by simonvanderveldt** [comment]
Ohw, this was merged whilst I was typing the previous comment. I still think it's valid though. Can create a new PR to update if you guys want.

**Comment by javabrett** [comment]
@simonvanderveldt My main motivation was to provide a quick solution to the problem raised in #35.  I was playing around with some Gentoo-based images and wanted to see if I could install something from Portage into the image.

I completely agree that it is better to use the portage volume as a one-off just for building the image.  As the portage is available it can be used, and if you extend my example you can `rm -rf /usr/portage` afterwards as you suggest, then fold-down into the final image and not pay any image layer cost.

I think a PR would be great to make a comment that the portage becomes stale and should be removed, and your `emerge-webrsync` is good advice that I can now use too.

**Comment by simonvanderveldt** [comment]
Thx for the clarification :)

> I completely agree that it is better to use the portage volume as a one-off just for building the image. As the portage is available it can be used, and if you extend my example you can rm -rf /usr/portage afterwards as you suggest, then fold-down into the final image and not pay any image layer cost.

@javabrett how would you do this? Asking because I don't think it's possible because a `COPY` command always creates it's own layer, so removing what was added in the `COPY` command doesn't reduce the image size.
And afaik there's no way to copy the result from emerging the package in a clean way to the next stage because there's no way to create a single artifact that you can immediately install (apart from maybe extracting a binpkg, but I don't know if that will work in all cases).

**Comment by javabrett** [comment]
What about something like:

```
FROM gentoo/portage:latest as portage

FROM gentoo/stage3-amd64:latest as builder
COPY --from=portage /usr/portage /usr/portage
RUN emerge -v www-servers/apache
RUN rm -rf /usr/portage

FROM scratch
COPY --from=builder / /
```

**Comment by simonvanderveldt** [comment]
@javabrett interesting suggestion, never tried that. Does it work?
It will obviously mean there will just be 1 layer, so no cache of for example the stage3.

**Comment by javabrett** [comment]
Yes it works.  What's more, caching works as-normal but with a couple of slightly-expensive late-misses.  But they are cheaper than some `emerge`s.

Should you append another `emerge` (as a separate `RUN` instruction), that will be the first cache-miss, so you won't have to run all the previous `emerge`s.  Of course that will force the `RUN rm -rf /usr/portage` and the final root-root `COPY` to re-run, but that is fine.

The main point of the change was to show how a `build` workflow can use the `portage` volume efficiently.  The example could be improved by adding the clean-up.

**Comment by simonvanderveldt** [comment]
Cool! I'll give it a try. Can create a PR with some additions to the docs after that :)

**Pull request merged**
